import Head from 'next/head'
import Layout from '../components/Layout';
import { FavoritesContextProvider } from '../context/favoritesContext';
import '../styles/globals.css';

const App = ({ Component, pageProps }) => (
  <>
    <Head>
      <title>Recipe Viewer</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <FavoritesContextProvider>
        <Component {...pageProps} />
      </FavoritesContextProvider>
    </Layout>
  </>
);

export default App;
