import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Categories from '../components/Categories';
import { BASE_PHP_URL } from '../shared/helpers';

export default function Home({categories}) {

  return (
    <>
      <Head>
        <title>Recipe Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <h1 className={styles.title}>
          The best recipes
        </h1>
        <Categories categories={categories}/>
      </>
    </>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(BASE_PHP_URL);
  const products = await res.json();

  return {
    props: {
      categories: products.categories,
    },
  };
};
